[build.environment]
  NODE_VERSION = "20.11.1"

[build]
  command = "yarn install && yarn build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[dev]
  command = "npm run dev"
  port = 3000
