import {
  Home,
  Menu,
  X,
  Heart,
  Share2,
  Bed,
  Bath,
  Square,
  Check,
  Clock,
  Eye,
  Plus,
  User,
  Users,
  Tag,
  Key,
  LogOut,
  Settings,
  Loader2,
  Building,
  Building2,
  MapPin,
  Mail,
  Phone,
  DollarSign,
  Calendar,
  Star,
  Search,
  Filter,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  MoreHorizontal,
  Trash,
  Edit,
  Image as ImageIcon,
  Upload,
  Download,
  AlertCircle,
  Info,
  HelpCircle,
  ExternalLink,
} from "lucide-react";

export const Icons = {
  logo: Building2,
  menu: Menu,
  close: X,
  heart: Heart,
  share: Share2,
  bed: Bed,
  bath: Bath,
  squareFeet: Square,
  check: Check,
  clock: Clock,
  eye: Eye,
  plus: Plus,
  user: User,
  users: Users,
  tag: Tag,
  key: Key,
  logout: LogOut,
  settings: Settings,
  spinner: Loader2,
  building: Building,
  building2: Building2,
  mapPin: MapPin,
  mail: Mail,
  phone: Phone,
  dollar: DollarSign,
  calendar: Calendar,
  star: Star,
  search: Search,
  filter: Filter,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  more: MoreHorizontal,
  trash: Trash,
  edit: Edit,
  image: ImageIcon,
  upload: Upload,
  download: Download,
  alert: AlertCircle,
  info: Info,
  help: HelpCircle,
  external: ExternalLink,
  home: Home,
};
